version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuaSenhaForte123!
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  api:
    build: 
      context: ./ApiCrudDocker # Ajuste para o nome da pasta do seu projeto
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=ProductDb;User Id=sa;Password=SuaSenhaForte123!;TrustServerCertificate=True;
    depends_on:
      - sqlserver

volumes:
  sqlvolume: